<script setup lang="ts">
import { ref } from 'vue';

const openTab = ref(0);
</script>

<template>
  <section class="container mx-auto px-6 py-16">
    <p class="font-bold text-center text-lg text-purple-600">SETUP, EASY-PEASY!</p>
    <h2 class="font-bold mb-4 text-center text-4xl sm:text-5xl text-gray-900">
      Easiest way to setup
      <br />
      your HTML form.
    </h2>

    <p class="mb-4 text-center text-lg sm:text-xl text-gray-800">
      Don't worry about emails, spam checking, integrations, and form issues ever,
      <br />
      code your front-end, add your unique formcarry URL, and we'll handle the rest.
      <br />
      Within literally just 3 minutes, you can have a fully functional form for any platform.
    </p>
    
    <!-- Tab component -->
    <div class="font-sans flex flex-col sm:flex-row items-center justify-center">
      <div x-data="{ openTab: 1 }" class="p-4">
        <div class="mb-6 flex space-x-1 p-2 bg-white rounded-lg shadow-md">
          <button
            x-on:click="openTab = 1"
            :class="{ 'bg-blue-600 text-white': openTab === 1 }"
            class="flex-1 py-2 px-4 rounded-md focus:outline-none focus:shadow-outline-blue transition-all duration-300"
          >
            <div class="flex items-center space-x-2">
              <img src="/html.svg" alt="" />
              <p>HTML</p>
            </div>
          </button>
          <button
            x-on:click="openTab = 2"
            :class="{ 'bg-blue-600 text-white': openTab === 2 }"
            class="flex-1 py-2 px-4 rounded-md focus:outline-none focus:shadow-outline-blue transition-all duration-300"
          >
            <div class="flex items-center space-x-2">
              <img src="/Jquery.svg" alt="" />
              <p>jQuery</p>
            </div>
          </button>
          <button
            x-on:click="openTab = 3"
            :class="{ 'bg-blue-600 text-white': openTab === 3 }"
            class="flex-1 py-2 px-4 rounded-md focus:outline-none focus:shadow-outline-blue transition-all duration-300"
          >
            <div class="flex items-center space-x-2">
              <img src="/react.svg" alt="" />
              <p>React</p>
            </div>
          </button>
          <button
            x-on:click="openTab = 4"
            :class="{ 'bg-blue-600 text-white': openTab === 4 }"
            class="flex-1 py-2 px-4 rounded-md focus:outline-none focus:shadow-outline-blue transition-all duration-300"
          >
            <div class="flex items-center space-x-2">
              <img src="/vue.svg" alt="" />
              <p>Vue</p>
            </div>
          </button>
        </div>

        <!-- Tab Content -->
        <div class="max-w-2xl mx-auto mt-12 relative w-full h-96 overflow-y-auto p-4">
          <div class="bg-gray-100 rounded-lg shadow-sm relative z-10">
            <div class="border-b border-gray-100 p-4">
              <div class="flex items-center space-x-2">
                <div class="w-3 h-3 rounded-full bg-red-400"></div>
                <div class="w-3 h-3 rounded-full bg-yellow-400"></div>
                <div class="w-3 h-3 rounded-full bg-green-400"></div>
                <div class="text-xs text-center py-1 px-2 bg-purple-600 text-white rounded-full">
                  VS Code
                </div>
              </div>
            </div>
            <div x-show="openTab === 1" class="p-6 font-mono text-sm transition-all duration-300 max-h-[400px] overflow-y-auto">
   
              <pre style="text-align:left;white-space:pre;word-spacing:normal;word-break:normal;word-wrap:normal;color:#F7F9FC;background:#F7F9FC;font-family:Roboto Mono, monospace;font-size:1em;line-height:1.5em;-moz-tab-size:4;-o-tab-size:4;tab-size:4;-webkit-hyphens:none;-moz-hyphens:none;-ms-hyphens:none;hyphens:none;overflow:auto;position:relative;margin:0;padding:16px 1em">
    <code class="language-html" style="text-align:left;white-space:pre;word-spacing:normal;word-break:normal;word-wrap:normal;color:#0E0B3D;background:#F7F9FC;font-family:Roboto Mono, monospace;font-size:1em;line-height:1.5em;-moz-tab-size:4;-o-tab-size:4;tab-size:4;-webkit-hyphens:none;-moz-hyphens:none;-ms-hyphens:none;hyphens:none">
<span><span class="linenumber react-syntax-highlighter-line-number" style="display:inline-block;min-width:17px;padding-right:1em;text-align:right;user-select:none;color:#aabfc9">1</span><span class="token token" style="color:#39adb5">&lt;</span><span class="token token" style="color:#1463FF">form</span><span class="token token" style="color:#1463FF"> </span><span class="token token" style="color:#39adb5">action</span><span class="token token attr-equals" style="color:#39adb5">=</span><span class="token token" style="color:#39adb5">"</span><span class="token token" style="color:#7214FF">https://formcarry.com/s/{Your Form ID}</span><span class="token token" style="color:#39adb5">"</span><span class="token token" style="color:#1463FF">
    </span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display:inline-block;min-width:17px;padding-right:1em;text-align:right;user-select:none;color:#aabfc9">2</span><span class="token token" style="color:#1463FF"></span><span class="token token" style="color:#39adb5">method</span><span class="token token attr-equals" style="color:#39adb5">=</span><span class="token token" style="color:#39adb5">"</span><span class="token token" style="color:#7214FF">POST</span><span class="token token" style="color:#39adb5">"</span><span class="token token" style="color:#1463FF"> </span><span class="token token" style="color:#39adb5">enctype</span><span class="token token attr-equals" style="color:#39adb5">=</span><span class="token token" style="color:#39adb5">"</span><span class="token token" style="color:#7214FF">multipart/form-data</span><span class="token token" style="color:#39adb5">"</span><span class="token token" style="color:#39adb5">&gt;</span><span>
    </span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display:inline-block;min-width:17px;padding-right:1em;text-align:right;user-select:none;color:#aabfc9">3</span><span>  </span><span class="token token" style="color:#39adb5">&lt;</span><span class="token token" style="color:#1463FF">input</span><span class="token token" style="color:#1463FF"> </span><span class="token token" style="color:#39adb5">type</span><span class="token token attr-equals" style="color:#39adb5">=</span><span class="token token" style="color:#39adb5">"</span><span class="token token" style="color:#7214FF">email</span><span class="token token" style="color:#39adb5">"</span><span class="token token" style="color:#1463FF"> </span><span class="token token" style="color:#39adb5">name</span><span class="token token attr-equals" style="color:#39adb5">=</span><span class="token token" style="color:#39adb5">"</span><span class="token token" style="color:#7214FF">email</span><span class="token token" style="color:#39adb5">"</span><span class="token token" style="color:#39adb5">&gt;</span><span>
    </span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display:inline-block;min-width:17px;padding-right:1em;text-align:right;user-select:none;color:#aabfc9">4</span>
    </span><span><span class="linenumber react-syntax-highlighter-line-number" style="display:inline-block;min-width:17px;padding-right:1em;text-align:right;user-select:none;color:#aabfc9">5</span><span>  </span><span class="token token" style="color:#39adb5">&lt;</span><span class="token token" style="color:#1463FF">textarea</span><span class="token token" style="color:#1463FF"> </span><span class="token token" style="color:#39adb5">name</span><span class="token token attr-equals" style="color:#39adb5">=</span><span class="token token" style="color:#39adb5">"</span><span class="token token" style="color:#7214FF">message</span><span class="token token" style="color:#39adb5">"</span><span class="token token" style="color:#39adb5">&gt;</span><span class="token token" style="color:#39adb5">&lt;/</span><span class="token token" style="color:#1463FF">textarea</span><span class="token token" style="color:#39adb5">&gt;</span><span>
    </span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display:inline-block;min-width:17px;padding-right:1em;text-align:right;user-select:none;color:#aabfc9">6</span><span>  </span><span class="token token" style="color:#39adb5">&lt;</span><span class="token token" style="color:#1463FF">button</span><span class="token token" style="color:#1463FF"> </span><span class="token token" style="color:#39adb5">type</span><span class="token token attr-equals" style="color:#39adb5">=</span><span class="token token" style="color:#39adb5">"</span><span class="token token" style="color:#7214FF">submit</span><span class="token token" style="color:#39adb5">"</span><span class="token token" style="color:#39adb5">&gt;</span><span>Submit</span><span class="token token" style="color:#39adb5">&lt;/</span><span class="token token" style="color:#1463FF">button</span><span class="token token" style="color:#39adb5">&gt;</span><span>
    </span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display:inline-block;min-width:17px;padding-right:1em;text-align:right;user-select:none;color:#aabfc9">7</span><span></span><span class="token token" style="color:#39adb5">&lt;/</span><span class="token token" style="color:#1463FF">form</span><span class="token token" style="color:#39adb5">&gt;</span></span>
    </code>
  </pre>

</div>

<div x-show="openTab === 2" class="p-6 font-mono text-sm transition-all duration-300 max-h-[400px] overflow-y-auto">
 


  <pre style="text-align: left; white-space: pre; word-spacing: normal; word-break: normal; overflow-wrap: normal; color: rgb(247, 249, 252); background: rgb(247, 249, 252); font-family: &quot;Roboto Mono&quot;, monospace; font-size: 1em; line-height: 1.5em; tab-size: 4; hyphens: none; overflow: auto; position: relative; margin: 0px; padding: 16px 1em;"><code class="language-html" style="text-align: left; white-space: pre; word-spacing: normal; word-break: normal; overflow-wrap: normal; color: rgb(14, 11, 61); background: rgb(247, 249, 252); font-family: &quot;Roboto Mono&quot;, monospace; font-size: 1em; line-height: 1.5em; tab-size: 4; hyphens: none;"><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">1</span><span class="token token" style="color: rgb(57, 173, 181);">&lt;</span><span class="token token" style="color: rgb(20, 99, 255);">form</span><span class="token token" style="color: rgb(20, 99, 255);"> 
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">2</span><span class="token token" style="color: rgb(20, 99, 255);">  </span><span class="token token" style="color: rgb(57, 173, 181);">class</span><span class="token token attr-equals" style="color: rgb(57, 173, 181);">=</span><span class="token token" style="color: rgb(57, 173, 181);">"</span><span class="token token" style="color: rgb(114, 20, 255);">ajaxForm</span><span class="token token" style="color: rgb(57, 173, 181);">"</span><span class="token token" style="color: rgb(20, 99, 255);"> 
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">3</span><span class="token token" style="color: rgb(20, 99, 255);">  </span><span class="token token" style="color: rgb(57, 173, 181);">action</span><span class="token token attr-equals" style="color: rgb(57, 173, 181);">=</span><span class="token token" style="color: rgb(57, 173, 181);">"</span><span class="token token" style="color: rgb(114, 20, 255);">https://formcarry.com/s/{Your Form ID}</span><span class="token token" style="color: rgb(57, 173, 181);">"</span><span class="token token" style="color: rgb(20, 99, 255);"> 
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">4</span><span class="token token" style="color: rgb(20, 99, 255);">  </span><span class="token token" style="color: rgb(57, 173, 181);">method</span><span class="token token attr-equals" style="color: rgb(57, 173, 181);">=</span><span class="token token" style="color: rgb(57, 173, 181);">"</span><span class="token token" style="color: rgb(114, 20, 255);">POST</span><span class="token token" style="color: rgb(57, 173, 181);">"</span><span class="token token" style="color: rgb(20, 99, 255);"> 
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">5</span><span class="token token" style="color: rgb(20, 99, 255);">  </span><span class="token token" style="color: rgb(57, 173, 181);">accept-charset</span><span class="token token attr-equals" style="color: rgb(57, 173, 181);">=</span><span class="token token" style="color: rgb(57, 173, 181);">"</span><span class="token token" style="color: rgb(114, 20, 255);">UTF-8</span><span class="token token" style="color: rgb(57, 173, 181);">"</span><span class="token token" style="color: rgb(20, 99, 255);"> 
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">6</span><span class="token token" style="color: rgb(20, 99, 255);">  </span><span class="token token" style="color: rgb(57, 173, 181);">enctype</span><span class="token token attr-equals" style="color: rgb(57, 173, 181);">=</span><span class="token token" style="color: rgb(57, 173, 181);">"</span><span class="token token" style="color: rgb(114, 20, 255);">multipart/form-data
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">7</span><span class="token token" style="color: rgb(114, 20, 255);"></span><span class="token token" style="color: rgb(57, 173, 181);">"</span><span class="token token" style="color: rgb(57, 173, 181);">&gt;</span><span>
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">8</span><span>  </span><span class="token token" style="color: rgb(57, 173, 181);">&lt;</span><span class="token token" style="color: rgb(20, 99, 255);">input</span><span class="token token" style="color: rgb(20, 99, 255);"> </span><span class="token token" style="color: rgb(57, 173, 181);">type</span><span class="token token attr-equals" style="color: rgb(57, 173, 181);">=</span><span class="token token" style="color: rgb(57, 173, 181);">"</span><span class="token token" style="color: rgb(114, 20, 255);">file</span><span class="token token" style="color: rgb(57, 173, 181);">"</span><span class="token token" style="color: rgb(20, 99, 255);"> </span><span class="token token" style="color: rgb(57, 173, 181);">name</span><span class="token token attr-equals" style="color: rgb(57, 173, 181);">=</span><span class="token token" style="color: rgb(57, 173, 181);">"</span><span class="token token" style="color: rgb(114, 20, 255);">picture</span><span class="token token" style="color: rgb(57, 173, 181);">"</span><span class="token token" style="color: rgb(57, 173, 181);">&gt;</span><span>
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">9</span><span>  </span><span class="token token" style="color: rgb(57, 173, 181);">&lt;</span><span class="token token" style="color: rgb(20, 99, 255);">input</span><span class="token token" style="color: rgb(20, 99, 255);"> </span><span class="token token" style="color: rgb(57, 173, 181);">type</span><span class="token token attr-equals" style="color: rgb(57, 173, 181);">=</span><span class="token token" style="color: rgb(57, 173, 181);">"</span><span class="token token" style="color: rgb(114, 20, 255);">submit</span><span class="token token" style="color: rgb(57, 173, 181);">"</span><span class="token token" style="color: rgb(20, 99, 255);"> </span><span class="token token" style="color: rgb(57, 173, 181);">value</span><span class="token token attr-equals" style="color: rgb(57, 173, 181);">=</span><span class="token token" style="color: rgb(57, 173, 181);">"</span><span class="token token" style="color: rgb(114, 20, 255);">Send</span><span class="token token" style="color: rgb(57, 173, 181);">"</span><span class="token token" style="color: rgb(57, 173, 181);">&gt;</span><span>
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">10</span><span></span><span class="token token" style="color: rgb(57, 173, 181);">&lt;/</span><span class="token token" style="color: rgb(20, 99, 255);">form</span><span class="token token" style="color: rgb(57, 173, 181);">&gt;</span><span>
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">11</span>
</span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">12</span><span></span><span class="token token" style="color: rgb(57, 173, 181);">&lt;</span><span class="token token" style="color: rgb(20, 99, 255);">script</span><span class="token token" style="color: rgb(20, 99, 255);"> </span><span class="token token" style="color: rgb(57, 173, 181);">src</span><span class="token token attr-equals" style="color: rgb(57, 173, 181);">=</span><span class="token token" style="color: rgb(57, 173, 181);">"</span><span class="token token" style="color: rgb(114, 20, 255);">https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js</span><span class="token token" style="color: rgb(57, 173, 181);">"</span><span class="token token" style="color: rgb(57, 173, 181);">&gt;</span><span class="token token" style="color: rgb(57, 173, 181);">&lt;/</span><span class="token token" style="color: rgb(20, 99, 255);">script</span><span class="token token" style="color: rgb(57, 173, 181);">&gt;</span><span>
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">13</span><span></span><span class="token token" style="color: rgb(57, 173, 181);">&lt;</span><span class="token token" style="color: rgb(20, 99, 255);">script</span><span class="token token" style="color: rgb(57, 173, 181);">&gt;</span><span class="token token script language-javascript">
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">14</span><span class="token token script language-javascript">  </span><span class="token token script language-javascript" style="color: rgb(114, 20, 255);">$</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">(</span><span class="token token script language-javascript" style="color: rgb(114, 20, 255);">function</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">(</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">)</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">{</span><span class="token token script language-javascript">
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">15</span><span class="token token script language-javascript">    </span><span class="token token script language-javascript" style="color: rgb(114, 20, 255);">$</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">(</span><span class="token token script language-javascript" style="color: rgb(114, 20, 255);">".ajaxForm"</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">)</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">.</span><span class="token token script language-javascript" style="color: rgb(114, 20, 255);">submit</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">(</span><span class="token token script language-javascript" style="color: rgb(114, 20, 255);">function</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">(</span><span class="token token script language-javascript parameter">e</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">)</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">{</span><span class="token token script language-javascript">
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">16</span><span class="token token script language-javascript">      e</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">.</span><span class="token token script language-javascript" style="color: rgb(114, 20, 255);">preventDefault</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">(</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">)</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">;</span><span class="token token script language-javascript">
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">17</span><span class="token token script language-javascript">      </span><span class="token token script language-javascript" style="color: rgb(114, 20, 255);">var</span><span class="token token script language-javascript"> href </span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">=</span><span class="token token script language-javascript"> </span><span class="token token script language-javascript" style="color: rgb(114, 20, 255);">$</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">(</span><span class="token token script language-javascript" style="color: rgb(114, 20, 255);">this</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">)</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">.</span><span class="token token script language-javascript" style="color: rgb(114, 20, 255);">attr</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">(</span><span class="token token script language-javascript" style="color: rgb(114, 20, 255);">"action"</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">)</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">;</span><span class="token token script language-javascript">
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">18</span><span class="token token script language-javascript">      $</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">.</span><span class="token token script language-javascript" style="color: rgb(114, 20, 255);">ajax</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">(</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">{</span><span class="token token script language-javascript">
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">19</span><span class="token token script language-javascript">        </span><span class="token token script language-javascript literal-property" style="color: rgb(57, 173, 181);">type</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">:</span><span class="token token script language-javascript"> </span><span class="token token script language-javascript" style="color: rgb(114, 20, 255);">"POST"</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">,</span><span class="token token script language-javascript">
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">20</span><span class="token token script language-javascript">        </span><span class="token token script language-javascript literal-property" style="color: rgb(57, 173, 181);">dataType</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">:</span><span class="token token script language-javascript"> </span><span class="token token script language-javascript" style="color: rgb(114, 20, 255);">"json"</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">,</span><span class="token token script language-javascript">
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">21</span><span class="token token script language-javascript">        </span><span class="token token script language-javascript literal-property" style="color: rgb(57, 173, 181);">url</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">:</span><span class="token token script language-javascript"> href</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">,</span><span class="token token script language-javascript">
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">22</span><span class="token token script language-javascript">        </span><span class="token token script language-javascript literal-property" style="color: rgb(57, 173, 181);">data</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">:</span><span class="token token script language-javascript"> </span><span class="token token script language-javascript" style="color: rgb(114, 20, 255);">$</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">(</span><span class="token token script language-javascript" style="color: rgb(114, 20, 255);">this</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">)</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">.</span><span class="token token script language-javascript" style="color: rgb(114, 20, 255);">serialize</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">(</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">)</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">,</span><span class="token token script language-javascript">
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">23</span><span class="token token script language-javascript">        </span><span class="token token script language-javascript function-variable" style="color: rgb(114, 20, 255);">success</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">:</span><span class="token token script language-javascript"> </span><span class="token token script language-javascript" style="color: rgb(114, 20, 255);">function</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">(</span><span class="token token script language-javascript parameter">response</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">)</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">{</span><span class="token token script language-javascript">
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">24</span><span class="token token script language-javascript">          </span><span class="token token script language-javascript" style="color: rgb(114, 20, 255);">if</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">(</span><span class="token token script language-javascript">response</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">.</span><span class="token token script language-javascript">status </span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">==</span><span class="token token script language-javascript"> </span><span class="token token script language-javascript" style="color: rgb(114, 20, 255);">"success"</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">)</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">{</span><span class="token token script language-javascript">
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">25</span><span class="token token script language-javascript">            </span><span class="token token script language-javascript" style="color: rgb(114, 20, 255);">alert</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">(</span><span class="token token script language-javascript" style="color: rgb(114, 20, 255);">"We received your submission, thank you!"</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">)</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">;</span><span class="token token script language-javascript">
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">26</span><span class="token token script language-javascript">          </span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">}</span><span class="token token script language-javascript" style="color: rgb(114, 20, 255);">else</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">{</span><span class="token token script language-javascript">
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">27</span><span class="token token script language-javascript">            </span><span class="token token script language-javascript" style="color: rgb(114, 20, 255);">alert</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">(</span><span class="token token script language-javascript" style="color: rgb(114, 20, 255);">"An error occured: "</span><span class="token token script language-javascript"> </span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">+</span><span class="token token script language-javascript"> response</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">.</span><span class="token token script language-javascript">message</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">)</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">;</span><span class="token token script language-javascript">
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">28</span><span class="token token script language-javascript">          </span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">}</span><span class="token token script language-javascript">
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">29</span><span class="token token script language-javascript">        </span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">}</span><span class="token token script language-javascript">
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">30</span><span class="token token script language-javascript">      </span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">}</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">)</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">;</span><span class="token token script language-javascript">
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">31</span><span class="token token script language-javascript">    </span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">}</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">)</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">;</span><span class="token token script language-javascript">
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">32</span><span class="token token script language-javascript">  </span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">}</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">)</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">;</span><span class="token token script language-javascript">
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">33</span><span class="token token script language-javascript"></span><span class="token token" style="color: rgb(57, 173, 181);">&lt;/</span><span class="token token" style="color: rgb(20, 99, 255);">script</span><span class="token token" style="color: rgb(57, 173, 181);">&gt;</span><span>
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">34</span></span></code></pre>



</div>

<div x-show="openTab === 3" class="p-6 font-mono text-sm transition-all duration-300 max-h-[400px] overflow-y-auto">
  

 <pre style="text-align: left; white-space: pre; word-spacing: normal; word-break: normal; overflow-wrap: normal; color: rgb(247, 249, 252); background: rgb(247, 249, 252); font-family: &quot;Roboto Mono&quot;, monospace; font-size: 1em; line-height: 1.5em; tab-size: 4; hyphens: none; overflow: auto; position: relative; margin: 0px; padding: 16px 1em;"><code class="language-jsx" style="text-align: left; white-space: pre; word-spacing: normal; word-break: normal; overflow-wrap: normal; color: rgb(14, 11, 61); background: rgb(247, 249, 252); font-family: &quot;Roboto Mono&quot;, monospace; font-size: 1em; line-height: 1.5em; tab-size: 4; hyphens: none;"><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">1</span><span class="token token" style="color: rgb(114, 20, 255);">import</span><span> React </span><span class="token token" style="color: rgb(114, 20, 255);">from</span><span> </span><span class="token token" style="color: rgb(114, 20, 255);">'react'</span><span class="token token" style="color: rgb(57, 173, 181);">;</span><span>
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">2</span><span></span><span class="token token" style="color: rgb(114, 20, 255);">import</span><span> </span><span class="token token" style="color: rgb(57, 173, 181);">{</span><span> useForm </span><span class="token token" style="color: rgb(57, 173, 181);">}</span><span> </span><span class="token token" style="color: rgb(114, 20, 255);">from</span><span> </span><span class="token token" style="color: rgb(114, 20, 255);">'@formcarry/react'</span><span class="token token" style="color: rgb(57, 173, 181);">;</span><span>
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">3</span>
</span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">4</span><span></span><span class="token token" style="color: rgb(114, 20, 255);">function</span><span> </span><span class="token token" style="color: rgb(114, 20, 255);">MyFormcarry</span><span class="token token" style="color: rgb(57, 173, 181);">(</span><span class="token token" style="color: rgb(57, 173, 181);">)</span><span> </span><span class="token token" style="color: rgb(57, 173, 181);">{</span><span>
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">5</span><span>  </span><span class="token token" style="color: rgb(170, 191, 201);">// Call the 'useForm' hook in your function component</span><span>
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">6</span><span>  </span><span class="token token" style="color: rgb(114, 20, 255);">const</span><span> </span><span class="token token" style="color: rgb(57, 173, 181);">{</span><span>state</span><span class="token token" style="color: rgb(57, 173, 181);">,</span><span> submit</span><span class="token token" style="color: rgb(57, 173, 181);">}</span><span> </span><span class="token token" style="color: rgb(57, 173, 181);">=</span><span> </span><span class="token token" style="color: rgb(114, 20, 255);">useForm</span><span class="token token" style="color: rgb(57, 173, 181);">(</span><span class="token token" style="color: rgb(57, 173, 181);">{</span><span>
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">7</span><span>    </span><span class="token token literal-property" style="color: rgb(57, 173, 181);">id</span><span class="token token" style="color: rgb(57, 173, 181);">:</span><span> </span><span class="token token" style="color: rgb(114, 20, 255);">'Your Form ID'</span><span>
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">8</span><span>  </span><span class="token token" style="color: rgb(57, 173, 181);">}</span><span class="token token" style="color: rgb(57, 173, 181);">)</span><span class="token token" style="color: rgb(57, 173, 181);">;</span><span>
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">9</span>
</span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">10</span><span>  </span><span class="token token" style="color: rgb(170, 191, 201);">// Success message</span><span>
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">11</span><span>  </span><span class="token token" style="color: rgb(114, 20, 255);">if</span><span> </span><span class="token token" style="color: rgb(57, 173, 181);">(</span><span>state</span><span class="token token" style="color: rgb(57, 173, 181);">.</span><span>submitted</span><span class="token token" style="color: rgb(57, 173, 181);">)</span><span> </span><span class="token token" style="color: rgb(57, 173, 181);">{</span><span>
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">12</span><span>    </span><span class="token token" style="color: rgb(114, 20, 255);">return</span><span> </span><span class="token token" style="color: rgb(57, 173, 181);">&lt;</span><span class="token token" style="color: rgb(20, 99, 255);">div</span><span class="token token" style="color: rgb(57, 173, 181);">&gt;</span><span class="token token plain-text">Thank you! We received your submission.</span><span class="token token" style="color: rgb(57, 173, 181);">&lt;/</span><span class="token token" style="color: rgb(20, 99, 255);">div</span><span class="token token" style="color: rgb(57, 173, 181);">&gt;</span><span class="token token" style="color: rgb(57, 173, 181);">;</span><span>
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">13</span><span>  </span><span class="token token" style="color: rgb(57, 173, 181);">}</span><span>
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">14</span>
</span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">15</span><span>  </span><span class="token token" style="color: rgb(114, 20, 255);">return</span><span> </span><span class="token token" style="color: rgb(57, 173, 181);">(</span><span>
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">16</span><span>    </span><span class="token token" style="color: rgb(57, 173, 181);">&lt;</span><span class="token token" style="color: rgb(20, 99, 255);">form</span><span class="token token" style="color: rgb(20, 99, 255);"> </span><span class="token token" style="color: rgb(57, 173, 181);">onSubmit</span><span class="token token script language-javascript script-punctuation" style="color: rgb(20, 99, 255);">=</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">{</span><span class="token token script language-javascript" style="color: rgb(20, 99, 255);">submit</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">}</span><span class="token token" style="color: rgb(57, 173, 181);">&gt;</span><span class="token token plain-text">
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">17</span><span class="token token plain-text">      </span><span class="token token" style="color: rgb(57, 173, 181);">&lt;</span><span class="token token" style="color: rgb(20, 99, 255);">label</span><span class="token token" style="color: rgb(20, 99, 255);"> </span><span class="token token" style="color: rgb(57, 173, 181);">htmlFor</span><span class="token token attr-equals" style="color: rgb(57, 173, 181);">=</span><span class="token token" style="color: rgb(57, 173, 181);">"</span><span class="token token" style="color: rgb(114, 20, 255);">email</span><span class="token token" style="color: rgb(57, 173, 181);">"</span><span class="token token" style="color: rgb(57, 173, 181);">&gt;</span><span class="token token plain-text">Email</span><span class="token token" style="color: rgb(57, 173, 181);">&lt;/</span><span class="token token" style="color: rgb(20, 99, 255);">label</span><span class="token token" style="color: rgb(57, 173, 181);">&gt;</span><span class="token token plain-text">
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">18</span><span class="token token plain-text">      </span><span class="token token" style="color: rgb(57, 173, 181);">&lt;</span><span class="token token" style="color: rgb(20, 99, 255);">input</span><span class="token token" style="color: rgb(20, 99, 255);"> </span><span class="token token" style="color: rgb(57, 173, 181);">id</span><span class="token token attr-equals" style="color: rgb(57, 173, 181);">=</span><span class="token token" style="color: rgb(57, 173, 181);">"</span><span class="token token" style="color: rgb(114, 20, 255);">email</span><span class="token token" style="color: rgb(57, 173, 181);">"</span><span class="token token" style="color: rgb(20, 99, 255);"> </span><span class="token token" style="color: rgb(57, 173, 181);">type</span><span class="token token attr-equals" style="color: rgb(57, 173, 181);">=</span><span class="token token" style="color: rgb(57, 173, 181);">"</span><span class="token token" style="color: rgb(114, 20, 255);">email</span><span class="token token" style="color: rgb(57, 173, 181);">"</span><span class="token token" style="color: rgb(20, 99, 255);"> </span><span class="token token" style="color: rgb(57, 173, 181);">name</span><span class="token token attr-equals" style="color: rgb(57, 173, 181);">=</span><span class="token token" style="color: rgb(57, 173, 181);">"</span><span class="token token" style="color: rgb(114, 20, 255);">email</span><span class="token token" style="color: rgb(57, 173, 181);">"</span><span class="token token" style="color: rgb(57, 173, 181);">/&gt;</span><span class="token token plain-text">
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">19</span>
</span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">20</span><span class="token token plain-text">      </span><span class="token token" style="color: rgb(57, 173, 181);">&lt;</span><span class="token token" style="color: rgb(20, 99, 255);">label</span><span class="token token" style="color: rgb(20, 99, 255);"> </span><span class="token token" style="color: rgb(57, 173, 181);">htmlFor</span><span class="token token attr-equals" style="color: rgb(57, 173, 181);">=</span><span class="token token" style="color: rgb(57, 173, 181);">"</span><span class="token token" style="color: rgb(114, 20, 255);">message</span><span class="token token" style="color: rgb(57, 173, 181);">"</span><span class="token token" style="color: rgb(57, 173, 181);">&gt;</span><span class="token token plain-text">Message</span><span class="token token" style="color: rgb(57, 173, 181);">&lt;/</span><span class="token token" style="color: rgb(20, 99, 255);">label</span><span class="token token" style="color: rgb(57, 173, 181);">&gt;</span><span class="token token plain-text">
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">21</span><span class="token token plain-text">      </span><span class="token token" style="color: rgb(57, 173, 181);">&lt;</span><span class="token token" style="color: rgb(20, 99, 255);">textarea</span><span class="token token" style="color: rgb(20, 99, 255);"> </span><span class="token token" style="color: rgb(57, 173, 181);">id</span><span class="token token attr-equals" style="color: rgb(57, 173, 181);">=</span><span class="token token" style="color: rgb(57, 173, 181);">"</span><span class="token token" style="color: rgb(114, 20, 255);">message</span><span class="token token" style="color: rgb(57, 173, 181);">"</span><span class="token token" style="color: rgb(20, 99, 255);"> </span><span class="token token" style="color: rgb(57, 173, 181);">name</span><span class="token token attr-equals" style="color: rgb(57, 173, 181);">=</span><span class="token token" style="color: rgb(57, 173, 181);">"</span><span class="token token" style="color: rgb(114, 20, 255);">message</span><span class="token token" style="color: rgb(57, 173, 181);">"</span><span class="token token" style="color: rgb(57, 173, 181);">/&gt;</span><span class="token token plain-text">
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">22</span>
</span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">23</span><span class="token token plain-text">      </span><span class="token token" style="color: rgb(57, 173, 181);">&lt;</span><span class="token token" style="color: rgb(20, 99, 255);">button</span><span class="token token" style="color: rgb(20, 99, 255);"> </span><span class="token token" style="color: rgb(57, 173, 181);">type</span><span class="token token attr-equals" style="color: rgb(57, 173, 181);">=</span><span class="token token" style="color: rgb(57, 173, 181);">"</span><span class="token token" style="color: rgb(114, 20, 255);">submit</span><span class="token token" style="color: rgb(57, 173, 181);">"</span><span class="token token" style="color: rgb(57, 173, 181);">&gt;</span><span class="token token plain-text">Send</span><span class="token token" style="color: rgb(57, 173, 181);">&lt;/</span><span class="token token" style="color: rgb(20, 99, 255);">button</span><span class="token token" style="color: rgb(57, 173, 181);">&gt;</span><span class="token token plain-text">
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">24</span><span class="token token plain-text">    </span><span class="token token" style="color: rgb(57, 173, 181);">&lt;/</span><span class="token token" style="color: rgb(20, 99, 255);">form</span><span class="token token" style="color: rgb(57, 173, 181);">&gt;</span><span>
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">25</span><span>  </span><span class="token token" style="color: rgb(57, 173, 181);">)</span><span class="token token" style="color: rgb(57, 173, 181);">;</span><span>
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">26</span><span></span><span class="token token" style="color: rgb(57, 173, 181);">}</span></span></code></pre>

</div>

<div x-show="openTab === 4" class="p-6 font-mono text-sm transition-all duration-300 max-h-[400px] overflow-y-auto">

  <pre style="text-align: left; white-space: pre; word-spacing: normal; word-break: normal; overflow-wrap: normal; color: rgb(247, 249, 252); background: rgb(247, 249, 252); font-family: &quot;Roboto Mono&quot;, monospace; font-size: 1em; line-height: 1.5em; tab-size: 4; hyphens: none; overflow: auto; position: relative; margin: 0px; padding: 16px 1em;"><code class="language-html" style="text-align: left; white-space: pre; word-spacing: normal; word-break: normal; overflow-wrap: normal; color: rgb(14, 11, 61); background: rgb(247, 249, 252); font-family: &quot;Roboto Mono&quot;, monospace; font-size: 1em; line-height: 1.5em; tab-size: 4; hyphens: none;"><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">1</span><span class="token token" style="color: rgb(57, 173, 181);">&lt;</span><span class="token token" style="color: rgb(20, 99, 255);">template</span><span class="token token" style="color: rgb(57, 173, 181);">&gt;</span><span>
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">2</span><span>  </span><span class="token token" style="color: rgb(57, 173, 181);">&lt;</span><span class="token token" style="color: rgb(20, 99, 255);">form</span><span class="token token" style="color: rgb(20, 99, 255);"> </span><span class="token token" style="color: rgb(57, 173, 181);">@submit.prevent</span><span class="token token attr-equals" style="color: rgb(57, 173, 181);">=</span><span class="token token" style="color: rgb(57, 173, 181);">"</span><span class="token token" style="color: rgb(114, 20, 255);">submitForm</span><span class="token token" style="color: rgb(57, 173, 181);">"</span><span class="token token" style="color: rgb(57, 173, 181);">&gt;</span><span>
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">3</span><span>    </span><span class="token token" style="color: rgb(57, 173, 181);">&lt;</span><span class="token token" style="color: rgb(20, 99, 255);">label</span><span class="token token" style="color: rgb(57, 173, 181);">&gt;</span><span>
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">4</span><span>      </span><span class="token token" style="color: rgb(57, 173, 181);">&lt;</span><span class="token token" style="color: rgb(20, 99, 255);">span</span><span class="token token" style="color: rgb(57, 173, 181);">&gt;</span><span>Email</span><span class="token token" style="color: rgb(57, 173, 181);">&lt;/</span><span class="token token" style="color: rgb(20, 99, 255);">span</span><span class="token token" style="color: rgb(57, 173, 181);">&gt;</span><span>
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">5</span><span>      </span><span class="token token" style="color: rgb(57, 173, 181);">&lt;</span><span class="token token" style="color: rgb(20, 99, 255);">input</span><span class="token token" style="color: rgb(20, 99, 255);"> </span><span class="token token" style="color: rgb(57, 173, 181);">type</span><span class="token token attr-equals" style="color: rgb(57, 173, 181);">=</span><span class="token token" style="color: rgb(57, 173, 181);">"</span><span class="token token" style="color: rgb(114, 20, 255);">email</span><span class="token token" style="color: rgb(57, 173, 181);">"</span><span class="token token" style="color: rgb(20, 99, 255);"> </span><span class="token token" style="color: rgb(57, 173, 181);">name</span><span class="token token attr-equals" style="color: rgb(57, 173, 181);">=</span><span class="token token" style="color: rgb(57, 173, 181);">"</span><span class="token token" style="color: rgb(114, 20, 255);">email</span><span class="token token" style="color: rgb(57, 173, 181);">"</span><span class="token token" style="color: rgb(20, 99, 255);"> </span><span class="token token" style="color: rgb(57, 173, 181);">v-model</span><span class="token token attr-equals" style="color: rgb(57, 173, 181);">=</span><span class="token token" style="color: rgb(57, 173, 181);">"</span><span class="token token" style="color: rgb(114, 20, 255);">email</span><span class="token token" style="color: rgb(57, 173, 181);">"</span><span class="token token" style="color: rgb(20, 99, 255);"> </span><span class="token token" style="color: rgb(57, 173, 181);">/&gt;</span><span>
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">6</span><span>    </span><span class="token token" style="color: rgb(57, 173, 181);">&lt;/</span><span class="token token" style="color: rgb(20, 99, 255);">label</span><span class="token token" style="color: rgb(57, 173, 181);">&gt;</span><span>
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">7</span><span>    </span><span class="token token" style="color: rgb(57, 173, 181);">&lt;</span><span class="token token" style="color: rgb(20, 99, 255);">label</span><span class="token token" style="color: rgb(57, 173, 181);">&gt;</span><span>
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">8</span><span>      </span><span class="token token" style="color: rgb(57, 173, 181);">&lt;</span><span class="token token" style="color: rgb(20, 99, 255);">span</span><span class="token token" style="color: rgb(57, 173, 181);">&gt;</span><span>Message</span><span class="token token" style="color: rgb(57, 173, 181);">&lt;/</span><span class="token token" style="color: rgb(20, 99, 255);">span</span><span class="token token" style="color: rgb(57, 173, 181);">&gt;</span><span>
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">9</span><span>      </span><span class="token token" style="color: rgb(57, 173, 181);">&lt;</span><span class="token token" style="color: rgb(20, 99, 255);">textarea</span><span class="token token" style="color: rgb(20, 99, 255);"> </span><span class="token token" style="color: rgb(57, 173, 181);">name</span><span class="token token attr-equals" style="color: rgb(57, 173, 181);">=</span><span class="token token" style="color: rgb(57, 173, 181);">"</span><span class="token token" style="color: rgb(114, 20, 255);">message</span><span class="token token" style="color: rgb(57, 173, 181);">"</span><span class="token token" style="color: rgb(20, 99, 255);"> </span><span class="token token" style="color: rgb(57, 173, 181);">v-model</span><span class="token token attr-equals" style="color: rgb(57, 173, 181);">=</span><span class="token token" style="color: rgb(57, 173, 181);">"</span><span class="token token" style="color: rgb(114, 20, 255);">message</span><span class="token token" style="color: rgb(57, 173, 181);">"</span><span class="token token" style="color: rgb(57, 173, 181);">&gt;</span><span class="token token" style="color: rgb(57, 173, 181);">&lt;/</span><span class="token token" style="color: rgb(20, 99, 255);">textarea</span><span class="token token" style="color: rgb(57, 173, 181);">&gt;</span><span>
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">10</span><span>    </span><span class="token token" style="color: rgb(57, 173, 181);">&lt;/</span><span class="token token" style="color: rgb(20, 99, 255);">label</span><span class="token token" style="color: rgb(57, 173, 181);">&gt;</span><span>
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">11</span><span>    </span><span class="token token" style="color: rgb(57, 173, 181);">&lt;</span><span class="token token" style="color: rgb(20, 99, 255);">button</span><span class="token token" style="color: rgb(20, 99, 255);"> </span><span class="token token" style="color: rgb(57, 173, 181);">type</span><span class="token token attr-equals" style="color: rgb(57, 173, 181);">=</span><span class="token token" style="color: rgb(57, 173, 181);">"</span><span class="token token" style="color: rgb(114, 20, 255);">submit</span><span class="token token" style="color: rgb(57, 173, 181);">"</span><span class="token token" style="color: rgb(57, 173, 181);">&gt;</span><span>Submit</span><span class="token token" style="color: rgb(57, 173, 181);">&lt;/</span><span class="token token" style="color: rgb(20, 99, 255);">button</span><span class="token token" style="color: rgb(57, 173, 181);">&gt;</span><span>
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">12</span><span>  </span><span class="token token" style="color: rgb(57, 173, 181);">&lt;/</span><span class="token token" style="color: rgb(20, 99, 255);">form</span><span class="token token" style="color: rgb(57, 173, 181);">&gt;</span><span>
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">13</span><span></span><span class="token token" style="color: rgb(57, 173, 181);">&lt;/</span><span class="token token" style="color: rgb(20, 99, 255);">template</span><span class="token token" style="color: rgb(57, 173, 181);">&gt;</span><span>
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">14</span>
</span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">15</span><span></span><span class="token token" style="color: rgb(57, 173, 181);">&lt;</span><span class="token token" style="color: rgb(20, 99, 255);">script</span><span class="token token" style="color: rgb(57, 173, 181);">&gt;</span><span class="token token script language-javascript">
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">16</span><span class="token token script language-javascript"></span><span class="token token script language-javascript" style="color: rgb(114, 20, 255);">export</span><span class="token token script language-javascript"> </span><span class="token token script language-javascript" style="color: rgb(114, 20, 255);">default</span><span class="token token script language-javascript"> </span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">{</span><span class="token token script language-javascript">
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">17</span><span class="token token script language-javascript">  </span><span class="token token script language-javascript" style="color: rgb(114, 20, 255);">data</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">(</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">)</span><span class="token token script language-javascript"> </span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">{</span><span class="token token script language-javascript">
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">18</span><span class="token token script language-javascript">    </span><span class="token token script language-javascript" style="color: rgb(114, 20, 255);">return</span><span class="token token script language-javascript"> </span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">{</span><span class="token token script language-javascript">
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">19</span><span class="token token script language-javascript">      </span><span class="token token script language-javascript literal-property" style="color: rgb(57, 173, 181);">email</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">:</span><span class="token token script language-javascript"> </span><span class="token token script language-javascript" style="color: rgb(114, 20, 255);">''</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">,</span><span class="token token script language-javascript">
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">20</span><span class="token token script language-javascript">      </span><span class="token token script language-javascript literal-property" style="color: rgb(57, 173, 181);">message</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">:</span><span class="token token script language-javascript"> </span><span class="token token script language-javascript" style="color: rgb(114, 20, 255);">''</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">,</span><span class="token token script language-javascript">
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">21</span><span class="token token script language-javascript">      </span><span class="token token script language-javascript literal-property" style="color: rgb(57, 173, 181);">endpoint</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">:</span><span class="token token script language-javascript"> </span><span class="token token script language-javascript" style="color: rgb(114, 20, 255);">'https://formcarry.com/s/{Your Form ID}'</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">,</span><span class="token token script language-javascript">
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">22</span><span class="token token script language-javascript">    </span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">}</span><span class="token token script language-javascript">
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">23</span><span class="token token script language-javascript">  </span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">}</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">,</span><span class="token token script language-javascript">
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">24</span><span class="token token script language-javascript">  </span><span class="token token script language-javascript literal-property" style="color: rgb(57, 173, 181);">methods</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">:</span><span class="token token script language-javascript"> </span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">{</span><span class="token token script language-javascript">
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">25</span><span class="token token script language-javascript">    </span><span class="token token script language-javascript" style="color: rgb(114, 20, 255);">async</span><span class="token token script language-javascript"> </span><span class="token token script language-javascript" style="color: rgb(114, 20, 255);">submitForm</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">(</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">)</span><span class="token token script language-javascript"> </span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">{</span><span class="token token script language-javascript">
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">26</span><span class="token token script language-javascript">      </span><span class="token token script language-javascript" style="color: rgb(114, 20, 255);">const</span><span class="token token script language-javascript"> data </span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">=</span><span class="token token script language-javascript"> </span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">{</span><span class="token token script language-javascript">
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">27</span><span class="token token script language-javascript">        </span><span class="token token script language-javascript literal-property" style="color: rgb(57, 173, 181);">email</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">:</span><span class="token token script language-javascript"> </span><span class="token token script language-javascript" style="color: rgb(114, 20, 255);">this</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">.</span><span class="token token script language-javascript">email</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">,</span><span class="token token script language-javascript">
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">28</span><span class="token token script language-javascript">        </span><span class="token token script language-javascript literal-property" style="color: rgb(57, 173, 181);">message</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">:</span><span class="token token script language-javascript"> </span><span class="token token script language-javascript" style="color: rgb(114, 20, 255);">this</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">.</span><span class="token token script language-javascript">message</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">,</span><span class="token token script language-javascript">
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">29</span><span class="token token script language-javascript">      </span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">}</span><span class="token token script language-javascript">
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">30</span><span class="token token script language-javascript">      </span><span class="token token script language-javascript" style="color: rgb(114, 20, 255);">const</span><span class="token token script language-javascript"> response </span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">=</span><span class="token token script language-javascript"> </span><span class="token token script language-javascript" style="color: rgb(114, 20, 255);">await</span><span class="token token script language-javascript"> </span><span class="token token script language-javascript" style="color: rgb(114, 20, 255);">this</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">.</span><span class="token token script language-javascript">$axios</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">.</span><span class="token token script language-javascript" style="color: rgb(114, 20, 255);">post</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">(</span><span class="token token script language-javascript" style="color: rgb(114, 20, 255);">this</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">.</span><span class="token token script language-javascript">endpoint</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">,</span><span class="token token script language-javascript"> data</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">)</span><span class="token token script language-javascript">
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">31</span><span class="token token script language-javascript">    </span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">}</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">,</span><span class="token token script language-javascript">
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">32</span><span class="token token script language-javascript">  </span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">}</span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">,</span><span class="token token script language-javascript">
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">33</span><span class="token token script language-javascript"></span><span class="token token script language-javascript" style="color: rgb(57, 173, 181);">}</span><span class="token token script language-javascript">
</span></span><span><span class="linenumber react-syntax-highlighter-line-number" style="display: inline-block; min-width: 17px; padding-right: 1em; text-align: right; user-select: none; color: rgb(170, 191, 201);">34</span><span class="token token script language-javascript"></span><span class="token token" style="color: rgb(57, 173, 181);">&lt;/</span><span class="token token" style="color: rgb(20, 99, 255);">script</span><span class="token token" style="color: rgb(57, 173, 181);">&gt;</span></span></code></pre>  
</div>

          </div>
        </div>
      </div>
    </div>

    <!-- Setup Button -->
    <div class="flex justify-center mt-8">
      <button
        style="background-color: rgb(14, 11, 61);"
        class="transition-all duration-300 py-3 px-6 text-white rounded-full text-lg flex items-center space-x-2"
      >
        <p>Setup Vue Form</p>
        <span>
          <svg
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
            class="text-white"
          >
            <path
              d="M12.172 11.9998L9.343 9.17184L10.757 7.75684L15 11.9998L10.757 16.2428L9.343 14.8278L12.172 11.9998Z"
              fill="#0E0B3D"
            />
          </svg>
        </span>
      </button>
    </div>
  </section>
</template>

<style scoped>
/* You can add specific styles here, if needed */
</style>
